In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import numpy as np
from PIL import Image

In [39]:


# open the cover image
cover_image = Image.open("/content/drive/MyDrive/Colab Notebooks/Steganography/Nikesh.jpg")

# convert the cover image to RGB format
cover_image = cover_image.convert('RGB')

# open the text file and read its contents
secret_text = 'Bad Boy Biplov'

# convert the secret text to binary
secret_text_binary = ''.join(format(ord(char), '08b') for char in secret_text)

# calculate the maximum number of bits that can be hidden in the cover image
max_bits = cover_image.width * cover_image.height * 3 // 8

# make sure that the secret text can be hidden in the cover image
if len(secret_text_binary) > max_bits:
    print("Error: The secret text is too long to be hidden in the cover image.")
    exit()

# hide the secret text in the LSBs of the cover image

for band in range(3):
    pixel = list(cover_image.getdata(band))
    for char in secret_text_binary:
        pixel[band] = (pixel[band] & 254) | int(char)
        cover_image.putdata(tuple(pixel), band)


# save the stego image
cover_image.save("stego_image.jpg")


In [40]:
cover_image = Image.open("/content/drive/MyDrive/Colab Notebooks/Steganography/Nikesh.jpg")

In [26]:
np.array(cover_image)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [29]:
secret_text_binary

'0100001001100001011001000010000001000010011011110111100100100000010000100110100101110000011011000110111101110110'

In [41]:
(pixel[670])

0

In [42]:
list(cover_image.getdata(0))

[204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 206,
 206,
 206,
 206,
 206,
 206,
 206,
 206,
 203,
 203,
 203,
 203,
 203,
 203,
 203,
 203,
 205,
 205,
 204,
 204,
 204,
 205,
 205,
 206,
 206,
 206,
 206,
 205,
 204,
 204,
 203,
 203,
 203,
 203,
 204,
 204,
 204,
 203,
 202,
 201,
 201,
 201,
 202,
 203,
 204,
 205,
 205,
 206,
 202,
 202,
 202,
 202,
 203,
 204,
 205,
 205,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 205,
 205,
 205,
 205,
 205,
 205,
 205,
 205,
 205,
 205,
 205,
 205,
 205,
 205,
 205,
 205,
 203,
 203,
 203,
 203,
 203,
 203,
 203,
 203,
 205,
 205,
 206,
 206,
 206,
 206,
 205,
 205,
 206,
 206,
 206,
 206,
 206,
 206,
 206,
 206,
 204,
 204,
 205,
 205,
 206,
 207,
 207,
 207,
 205,
 204,
 204,
 204,
 205,
 206,
 207,
 208,
 207,
 207,
 206,
 206,
 205,
 204,
 204,
 203,
 207,
 207,
 207,
 208,
 208,
 209,
 209

In [20]:
pixel = list(cover_image.getdata(0))

In [21]:
pixel_index

3

In [15]:
def recover_text(image):
    # Convert image to binary
    binary_image = np.unpackbits(image)

    # Extract embedded text from binary image
    binary_text = ''
    for i in range(len(binary_image)):
        if i % 8 == 0:
            binary_text += str(binary_image[i] & 1)
    text = ''.join(chr(int(binary_text[i:i+8], 2)) for i in range(0, len(binary_text), 8))

    return text

In [5]:
image = Image.open('/content/drive/MyDrive/Colab Notebooks/Steganography/Nikesh.jpg')

In [14]:
stegoimage = embed_text(image, 'hi there')

[1 1 0 ... 1 1 0]


In [16]:
text = recover_text(stegoimage)
text

'\x00ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ

In [11]:
stegoimage = Image.fromarray(stegoimage, "RGB")


IndexError: ignored

In [12]:
print(stegoimage)

[104 105  32 ... 100 106 142]
