<h1>To mount drive</h1>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
# to change the working directory
%cd /content/drive/MyDrive/Colab Notebooks/Steganography

/content/drive/.shortcut-targets-by-id/1oaZCwXh2SHDAQ3FtWzvS1pKkn3EYFRo1/Colab Notebooks/Steganography


<h1>The Imports</h1>

In [72]:
!pip install pycryptodomex

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 23.9 MB/s eta 0:00:00


In [73]:
import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np 
import pandas as pd
import torchvision
import matplotlib.pyplot as plt
from PIL import Image
import tempfile
import cv2
import subprocess
import random
import binascii
from base64 import b64encode, b64decode
import hashlib
from Cryptodome.Cipher import AES
from Cryptodome.Random import get_random_bytes

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tempfile.tempdir = "/tmp"

<h1>To Extract Audio From Video</h1>

In [6]:
!pip install ffmpeg

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for ffmpeg: filename=ffmpeg-1.4-py3-none-any.whl size=6084 sha256=dde8bf1c4c5a1ca2087e8a0c784d7bda4f2b46572e6015088e030a255680fbb2
  Stored in directory: /root/.cache/pip/wheels/30/33/46/5ab7eca55b9490dddbf3441c68a29535996270ef1ce8b9b6d7
Successfully built ffmpeg


In [7]:
# To extract audio from video 

def convert_video_to_audio(video_file, output_ext="wav"):
    filename, ext = os.path.splitext(video_file)
    subprocess.call(["ffmpeg", "-y", "-i", video_file, f"{filename}.{output_ext}"], 
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.STDOUT)






In [8]:
vf = 'Video and Audio files/covervid.mp4'
convert_video_to_audio(vf)

<h1> To hide Meta data </h1>

<h2> Text in image </h2>

In [74]:
DIST = 8


def normalize_pixel(r, g, b):
 
    if is_modify_pixel(r, g, b):
        seed = random.randint(1, 3)
        if seed == 1:
            r = _normalize(r)
        if seed == 2:
            g = _normalize(g)
        if seed == 3:
            b = _normalize(b)
    return r, g, b


def modify_pixel(r, g, b):
  
    return map(_modify, [r, g, b])


def is_modify_pixel(r, g, b):
   
    return r % DIST == g % DIST == b % DIST == 1


def _modify(i):
    if i >= 128:
        for x in range(DIST + 1):
            if i % DIST == 1:
                return i
            i -= 1
    else:
        for x in range(DIST + 1):
            if i % DIST == 1:
                return i
            i += 1
    raise ValueError


def _normalize(i):
    if i >= 128:
        i -= 1
    else:
        i += 1
    return i


def normalize(path, output):
  
    img = Image.open(path)
    img = img.convert('RGB')
    size = img.size
    new_img = Image.new('RGB', size)

    for y in range(img.size[1]):
        for x in range(img.size[0]):
            r, g, b = img.getpixel((x, y))
            _r, _g, _b = normalize_pixel(r, g, b)
            new_img.putpixel((x, y), (_r, _g, _b))
    new_img.save(output, 'PNG', optimize=True)


def hide_text(path, text):

    text = str(text)

    # convert text to hex for write
    write_param = []
    _base = 0
    for _ in to_hex(text):
        write_param.append(int(_, 16) + _base)
        _base += 16

    # hide hex-text to image
    img = Image.open(path)
    counter = 0
    for y in range(img.size[1]):
        for x in range(img.size[0]):
            if counter in write_param:
                r, g, b = img.getpixel((x, y))
                r, g, b = modify_pixel(r, g, b)
                img.putpixel((x, y), (r, g, b))
            counter += 1

    # save
    img.save(path,'PNG', optimize=True)

def to_hex(s):
    return binascii.hexlify(s.encode()).decode()

def to_str(s):
    return binascii.unhexlify(s).decode()

def read_text(path):
 
    img = Image.open(path)
    counter = 0
    result = []
    for y in range(img.size[1]):
        for x in range(img.size[0]):
            r, g, b = img.getpixel((x, y))
            if is_modify_pixel(r, g, b):
                result.append(counter)
            counter += 1
            if counter == 16:
                counter = 0
    return to_str(''.join([hex(_)[-1:] for _ in result]))


class Text_Steganography(object):
    @classmethod
    def encode(cls, input_image_path, output_image_path, encode_text):
        
        normalize(input_image_path, output_image_path)
        hide_text(output_image_path, encode_text)
        assert read_text(output_image_path) == encode_text, read_text(output_image_path)

    @classmethod
    def decode(cls, image_path):
        
        return read_text(image_path)

<h2> Encryption-Decryption </h2>

In [75]:
def tostring(lst):
    return ','.join(str(x) for x in lst)

def tolist(str):
    return str.split(',')
    
# define encrypt
def encrypt(plain_text, password):
    # generate a random salt
    salt = get_random_bytes(AES.block_size)

    # use the Scrypt KDF to get a private key from the password
    private_key = hashlib.scrypt(
        password.encode(), salt=salt, n=2**14, r=8, p=1, dklen=32)

    # create cipher config
    cipher_config = AES.new(private_key, AES.MODE_GCM)

    # return a dictionary with the encrypted text
    cipher_text, tag = cipher_config.encrypt_and_digest(bytes(plain_text, 'utf-8'))
    return [
        b64encode(cipher_text).decode('utf-8'),
        b64encode(salt).decode('utf-8'),
        b64encode(cipher_config.nonce).decode('utf-8'),
        b64encode(tag).decode('utf-8')
    ]

# define decrypt
def decrypt(enc_list, password):
    # decode the dictionary entries from base64
    salt = b64decode(enc_list[1])
    cipher_text = b64decode(enc_list[0])
    nonce = b64decode(enc_list[2])
    tag = b64decode(enc_list[3])
    

    # generate the private key from the password and salt
    private_key = hashlib.scrypt(
        password.encode(), salt=salt, n=2**14, r=8, p=1, dklen=32)

    # create the cipher config
    cipher = AES.new(private_key, AES.MODE_GCM, nonce=nonce)

    # decrypt the cipher text
    decrypted = cipher.decrypt_and_verify(cipher_text, tag)

    return decrypted

<h1>To Hide Video </h1>

In [10]:

IMG_SIZE = 64
LEARNING_RATE  = 0.001
COVER_LOSS_WEIGHT = 1
SECRET_LOSS_WEIGHT = 1
TRAIN_BATCH_SIZE = 16
VALID_BATCH_SIZE = 1
EPOCHS = 1000
DECODER_LOSS_WEIGHT = 1

In [12]:
class PrepNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=3,out_channels=10,kernel_size=(3,3),stride=1,padding=1)
        self.conv2 = nn.Conv2d(in_channels=3,out_channels=20,kernel_size=(3,3),stride=1,padding=1)
        self.conv3 = nn.Conv2d(in_channels=3,out_channels=5,kernel_size=(5,5),stride=1,padding=2)
        
        self.conv4 = nn.Conv2d(in_channels=35,out_channels=10,kernel_size=(3,3),stride=1,padding=1)
        self.conv5 = nn.Conv2d(in_channels=35,out_channels=20,kernel_size=(3,3),stride=1,padding=1)
        self.conv6 = nn.Conv2d(in_channels=35,out_channels=5,kernel_size=(5,5),stride=1,padding=2)
    
    def forward(self,secret_image):
        output_1 = F.relu(self.conv1(secret_image))
        output_2 = F.relu(self.conv2(secret_image))
        output_3 = F.relu(self.conv3(secret_image))
        
        concatenated_image = torch.cat([output_1,output_2,output_3],dim=1)
        output_4 = F.relu(self.conv4(concatenated_image))
        output_5 = F.relu(self.conv5(concatenated_image))
        output_6 = F.relu(self.conv6(concatenated_image))
        
        final_concat_image = torch.cat([output_4,output_5,output_6],dim=1)
        return final_concat_image

class HidingNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=38,out_channels=10,kernel_size=(3,3),stride=1,padding=1)
        self.conv2 = nn.Conv2d(in_channels=38,out_channels=20,kernel_size=(3,3),stride=1,padding=1)
        self.conv3 = nn.Conv2d(in_channels=38,out_channels=5,kernel_size=(5,5),stride=1,padding=2)
        
        self.conv4 = nn.Conv2d(in_channels=35,out_channels=10,kernel_size=(3,3),stride=1,padding=1)
        self.conv5 = nn.Conv2d(in_channels=35,out_channels=20,kernel_size=(3,3),stride=1,padding=1)
        self.conv6 = nn.Conv2d(in_channels=35,out_channels=5,kernel_size=(5,5),stride=1,padding=2)
        
        self.conv7 = nn.Conv2d(in_channels=35,out_channels=10,kernel_size=(3,3),stride=1,padding=1)
        self.conv8 = nn.Conv2d(in_channels=35,out_channels=20,kernel_size=(3,3),stride=1,padding=1)
        self.conv9 = nn.Conv2d(in_channels=35,out_channels=5,kernel_size=(5,5),stride=1,padding=2)
        
        self.final_layer = nn.Conv2d(in_channels=35,out_channels=3,kernel_size=(3,3),stride=1,padding=1)
        
    def forward(self,secret_image,cover_image):
        concatenated_secrets = torch.cat([cover_image,secret_image],dim=1)
        
        output_1 = F.relu(self.conv1(concatenated_secrets))
        output_2 = F.relu(self.conv2(concatenated_secrets))
        output_3 = F.relu(self.conv3(concatenated_secrets))
        concat_1 = torch.cat([output_1,output_2,output_3],dim=1)
        
        output_4 = F.relu(self.conv4(concat_1))
        output_5 = F.relu(self.conv5(concat_1))
        output_6 = F.relu(self.conv6(concat_1))
        concat_2 = torch.cat([output_4,output_5,output_6],dim=1)
        
        output_7 = F.relu(self.conv7(concat_2))
        output_8 = F.relu(self.conv8(concat_2))
        output_9 = F.relu(self.conv9(concat_2))
        concat_3 = torch.cat([output_7,output_8,output_9],dim=1)
        output_converted_image = F.relu(self.final_layer(concat_3))
        
        return output_converted_image

In [13]:
class Encoder(nn.Module):
    def __init__(self,prep_network,hiding_network):
        super().__init__()
        self.prep_network = prep_network
        self.hiding_network = hiding_network
    
    def forward(self,cover_image,secret_image):
        encoded_secret_image = self.prep_network(secret_image)
        
        hidden_image = self.hiding_network(encoded_secret_image,
                                           cover_image
                                          )
#         hidden_image = (0.01**0.5)*torch.randn(hidden_image.size(),device=device)
        return hidden_image

In [14]:
class RevealNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=3,out_channels=10,kernel_size=(3,3),stride=1,padding=1)
        self.conv2 = nn.Conv2d(in_channels=3,out_channels=20,kernel_size=(3,3),stride=1,padding=1)
        self.conv3 = nn.Conv2d(in_channels=3,out_channels=5,kernel_size=(5,5),stride=1,padding=2)
        
        self.conv4 = nn.Conv2d(in_channels=35,out_channels=10,kernel_size=(3,3),stride=1,padding=1)
        self.conv5 = nn.Conv2d(in_channels=35,out_channels=20,kernel_size=(3,3),stride=1,padding=1)
        self.conv6 = nn.Conv2d(in_channels=35,out_channels=5,kernel_size=(5,5),stride=1,padding=2)
        
        self.conv7 = nn.Conv2d(in_channels=35,out_channels=10,kernel_size=(3,3),stride=1,padding=1)
        self.conv8 = nn.Conv2d(in_channels=35,out_channels=20,kernel_size=(3,3),stride=1,padding=1)
        self.conv9 = nn.Conv2d(in_channels=35,out_channels=5,kernel_size=(5,5),stride=1,padding=2)
        
        
        self.final_layer = nn.Conv2d(in_channels=35,out_channels=3,kernel_size=(3,3),stride=1,padding=1)    
    
    def forward(self,hidden_image):
        
        output_1 = F.relu(self.conv1(hidden_image))
        output_2 = F.relu(self.conv2(hidden_image))
        output_3 = F.relu(self.conv3(hidden_image))
        concat_1 = torch.cat([output_1,output_2,output_3],dim=1)
        
        output_4 = F.relu(self.conv4(concat_1))
        output_5 = F.relu(self.conv5(concat_1))
        output_6 = F.relu(self.conv6(concat_1))
        concat_2 = torch.cat([output_4,output_5,output_6],dim=1)
        
        output_7 = F.relu(self.conv7(concat_2))
        output_8 = F.relu(self.conv8(concat_2))
        output_9 = F.relu(self.conv9(concat_2))
        concat_3 = torch.cat([output_7,output_8,output_9],dim=1)
        
        
        output_revealed_image = F.relu(self.final_layer(concat_3))
        
        return output_revealed_image

In [15]:
class Decoder(nn.Module):
    def __init__(self,reveal_network):
        super().__init__()
        self.reveal_network = reveal_network
    
    def forward(self,hidden_image):
        reveal_image = self.reveal_network(hidden_image)
        return reveal_image

In [16]:
class SteganoModel(nn.Module):
    def __init__(self,encoder,decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder
    
    def forward(self,cover_image,secret_image,hidden_image,mode):
        if mode == 'full':
            for param in self.encoder.parameters():
                param.requires_grad = True
            for param in self.decoder.parameters():
                param.requires_grad = False
            hidden_image = self.encoder(cover_image,secret_image)
            reveal_image = self.decoder(hidden_image)
            return hidden_image,reveal_image
        elif mode == 'encoder':
            for param in self.encoder.parameters():
                param.requires_grad = False
            for param in self.decoder.parameters():
                param.requires_grad = False
            hidden_image = self.encoder(cover_image,secret_image)
            return hidden_image
        elif mode == 'decoder':
            for param in self.encoder.parameters():
                param.requires_grad = False
            for param in self.decoder.parameters():
                param.requires_grad = True
            
            reveal_image = self.decoder(hidden_image)
            return reveal_image

In [17]:
prep_net = PrepNetwork()
hiding_network = HidingNetwork()

encoder = Encoder(prep_net,hiding_network)

reveal_net = RevealNetwork()


decoder = Decoder(reveal_net)

model = SteganoModel(encoder,decoder)
model.to(device)

SteganoModel(
  (encoder): Encoder(
    (prep_network): PrepNetwork(
      (conv1): Conv2d(3, 10, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(3, 20, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv3): Conv2d(3, 5, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
      (conv4): Conv2d(35, 10, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv5): Conv2d(35, 20, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv6): Conv2d(35, 5, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    )
    (hiding_network): HidingNetwork(
      (conv1): Conv2d(38, 10, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(38, 20, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv3): Conv2d(38, 5, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
      (conv4): Conv2d(35, 10, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv5): Conv2d(35, 20, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
   

In [21]:
model = torch.load('/content/drive/MyDrive/Colab Notebooks/Steganography/stegomodeltest.pkl')

In [102]:
def predict(model,cover, secret,mode):

    cover_image = cover
    cover_image = cover_image.to(device)
    secret_image_1 = secret
    secret_image_1 = secret_image_1.to(device)
    
    model.eval()
    if mode =='decoder':
      
      reveal_image_1= model(cover_image,cover_image,cover_image,mode)
      
      # dot_graph = torchviz.make_dot(model(cover_image,cover_image,cover_image,mode))
      # dot_graph.render("decoder.dot")
    elif mode =='encoder':
      hidden_image= model(cover_image,secret_image_1,secret_image_1,mode)
      # dot_graph = torchviz.make_dot(model(cover_image,secret_image_1,secret_image_1,mode))
      # dot_graph.render("encoder.dot")
    elif mode == "full":
      
      hidden_image,reveal_image_1= model(cover_image,secret_image_1,secret_image_1,mode)
      # dot_graph = torchviz.make_dot(model(cover_image,secret_image_1,secret_image_1,mode))
      # dot_graph.render("full.dot")
      
      cover_image = cover_image * 255
      cover_image = cover_image.to(torch.device('cpu'))
      cover_image = cover_image.detach().to(torch.long)
      secret_image_1 = secret_image_1 * 255
      secret_image_1 = secret_image_1.to(torch.device('cpu'))
      secret_image_1 = secret_image_1.detach().to(torch.long)
    if mode =='encoder' or mode == 'full':
      hidden_image[hidden_image>1] = 1
      hidden_image = hidden_image * 255
      hidden_image = hidden_image.to(torch.device('cpu'))
      hidden_image = hidden_image.detach().to(torch.long)
      h = hidden_image[0].permute(1,2,0).numpy()
      h = h.astype(np.uint8)
      
      if mode == 'encoder': return h
    if mode =='decoder' or mode == 'full':
      reveal_image_1[reveal_image_1>1] = 1
      reveal_image_1 = reveal_image_1 * 255
      reveal_image_1 = reveal_image_1.to(torch.device('cpu'))
      reveal_image_1 = reveal_image_1.detach().to(torch.long)
      r = reveal_image_1[0].permute(1,2,0).numpy()
      r = r.astype(np.uint8)
      
      if mode == 'decoder': return r
    return {
        'cover_image_grid':cover_image[0].permute(1,2,0).numpy(),
        'secret_image_1_grid':secret_image_1[0].permute(1,2,0).numpy(),
        'hidden_image_grid':h,
        'reveal_image_1_grid':r,
    }
    

In [55]:
# Creating temporary file and deleting it (experiment)

temp = tempfile.TemporaryFile()

try:
    a = np.array([[1, 2, 3],[4, 5, 6]])
    b = np.array([[45678,67 , 63],[14, 25, 36]])
    print("Original array:")
    print(a)
    print(a.shape)
    a_bytes = a.tobytes()
    b_bytes = b.tobytes()
    print(len(a_bytes))
    print(len(b_bytes))
    temp.write(a_bytes)
    temp.write(b_bytes)
    temp.seek(0)
    
    
    print("After loading, content of the temp file:")
    for i in range(2):
      read_bytes = temp.read(len(a_bytes))
      print("in the temp file: ", read_bytes)
      a2 = np.frombuffer(read_bytes, dtype=a.dtype)
      a2 = a2.reshape(a.shape)
      print(a2)
    #print(temp.read())
   
finally:
    temp.close()

Original array:
[[1 2 3]
 [4 5 6]]
(2, 3)
48
48
After loading, content of the temp file:
in the temp file:  b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00'
[[1 2 3]
 [4 5 6]]
in the temp file:  b'n\xb2\x00\x00\x00\x00\x00\x00C\x00\x00\x00\x00\x00\x00\x00?\x00\x00\x00\x00\x00\x00\x00\x0e\x00\x00\x00\x00\x00\x00\x00\x19\x00\x00\x00\x00\x00\x00\x00$\x00\x00\x00\x00\x00\x00\x00'
[[45678    67    63]
 [   14    25    36]]


In [103]:
def is_hideable(count1,count2):
  framediff = count1 - count2
  if framediff-1 < 0:
    hideable = False 
  else: 
    hideable = True 
  return hideable

import traceback

def Video_Encode(cover_vid_path, secret_vid_path, output_vid_path):

  cap1 = cv2.VideoCapture(cover_vid_path)
  fps1 = cap1.get(cv2.CAP_PROP_FPS)
  

  cap2 = cv2.VideoCapture(secret_vid_path)
  fps2 = cap2.get(cv2.CAP_PROP_FPS)
 

    
  
 
  temp_cover = tempfile.TemporaryFile()
  temp_secret = tempfile.TemporaryFile()
    
  try: 
    count1 = 0 
    count2 = 0

    # cover video to frames in a temporary file:
    while True:
      
      is_read, frame = cap1.read()
      if not is_read:
          # break out of the loop if there are no frames to read
        break
      if count1 == 0:
        
        first_cover_frame = frame
        count1 += 1
        continue
      
      temp_cover.write(frame.tobytes())
      count1 += 1
    
    print('total number of frames in cover =', count1)


    # secret video to frames in a temporary file:

  
    while True:
          is_read, frame = cap2.read()
          if not is_read:
              # break out of the loop if there are no frames to read
              break
          if count2 == 0:
            first_secret_frame = frame
          
          temp_secret.write(frame.tobytes())
          count2 += 1
    
    print('total number of frames in secret =', count2)


      
    if not (is_hideable(count1,count2)):
      print("The secret video can't be hidden in the cover video")

    else:

      # Read one by one and hide: 
      offset = random.randint(0, count1-2)
      meta = [count2, fps2, offset]
      cover_frame_bytes = first_cover_frame.tobytes()
      secret_frame_bytes = first_secret_frame.tobytes()
      
      dimension = tuple(reversed(first_cover_frame.shape[:2]))
      stego_vid = cv2.VideoWriter(output_vid_path, cv2.VideoWriter_fourcc(*'MP4V'), fps1, dimension)
      

      # hide metadata in the first frame:
      im = Image.fromarray(first_cover_frame)
      im.save('firstframe.png')
      metastr = tostring(meta)
      password = input("Input Password: ")
      encrypted = encrypt(metastr, password)
      text_to_hide = tostring(encrypted)
      Text_Steganography.encode('firstframe.png','Text_hidden_inside_firstframe.png',text_to_hide)
      firstframe = cv2.imread('Text_hidden_inside_firstframe.png')

      
      stego_vid.write(firstframe)
      
      

      offset_frame = len(cover_frame_bytes) * offset
      
      
      
      temp_cover.seek(offset_frame)
      temp_secret.seek(0)

      for i in range(count2):
        
        # read cover frame
        read_cover_bytes = temp_cover.read(len(cover_frame_bytes))
        if read_cover_bytes == b'':
          temp_cover.seek(0)
          read_cover_bytes = temp_cover.read(len(cover_frame_bytes))
        cover_frame_obt = np.frombuffer(read_cover_bytes, dtype = first_cover_frame.dtype)
        cover_frame_obt = cover_frame_obt.reshape(first_cover_frame.shape)
        
        
        # read secret frame 
        read_secret_bytes = temp_secret.read(len(secret_frame_bytes))
        secret_frame_obt = np.frombuffer(read_secret_bytes, dtype = first_secret_frame.dtype)
        secret_frame_obt = secret_frame_obt.reshape(first_secret_frame.shape)
        
        
        #hide

        cover = Image.fromarray(cover_frame_obt)
        secret = Image.fromarray(secret_frame_obt)

        transform = torchvision.transforms.Compose([torchvision.transforms.Resize(cover.size),torchvision.transforms.ToTensor()])
        cover = transform(cover)
        secret = transform(secret)

        cover = cover.unsqueeze(0)
        secret = secret.unsqueeze(0)         
        stego_frame = predict(model, cover, secret,'encoder')

        

        # write stego_frame

        
        stego_vid.write(stego_frame)


      temp_cover.close()
      temp_secret.close()

      
      #release the stego video
      stego_vid.release()
      os.remove('firstframe.png')
      os.remove('Text_hidden_inside_firstframe.png')
      

  except Exception as e:
    print(traceback.format_exc())
    temp_cover.close()
    temp_secret.close()
    



    



In [ ]:
cover_vid_path = 'Video and Audio files/covervid.mp4'
secret_vid_path = 'Video and Audio files/secretvid.mp4'
output_vid_path = 'Video and Audio files/stegovid.mp4'

Video_Encode(cover_vid_path, secret_vid_path, output_vid_path)

<h1>To push this code to Github</h1>

In [105]:


%cd /content/drive/MyDrive
!git init 'Colab Notebooks'


%cd /content/drive/MyDrive/Colab Notebooks/Steganography/NOTEBOOKS

!git add .

!git commit -m "creation of video encoder"

!git config --global user.email "manohardahal40@gmail.com"
!git config --global user.name "manohar322028"

# unique personal access token should be generated each time before pushing, cause it can be used only one time.
# (I keep forgeting it lol) 
token = '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'
repo = 'https://'+ token + '@github.com/The-Byte-Builders/Multimedia-Steganography.git'

!git remote remove origin
!git remote add origin {repo}

!git remote -v

!git push origin master



/content/drive/MyDrive
Reinitialized existing Git repository in /content/drive/.shortcut-targets-by-id/1oaZCwXh2SHDAQ3FtWzvS1pKkn3EYFRo1/Colab Notebooks/.git/
/content/drive/.shortcut-targets-by-id/1oaZCwXh2SHDAQ3FtWzvS1pKkn3EYFRo1/Colab Notebooks/Steganography/NOTEBOOKS

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@49b07e2ac4bb.(none)')
origin	https://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@github.com/The-Byte-Builders/Multimedia-Steganography.git (fetch)
origin	https://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@github.com/The-Byte-Builders/Multimedia-Steganography.git (push)
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 

<h1> FINISHED </h1>